- name: Install Node.js, PM2 and MariaDB on App Tier
  hosts: app_servers
  become: yes

  tasks:

    # -----------------------------
    # Install MariaDB
    # -----------------------------
    - name: Install MariaDB server
      yum:
        name: mariadb-server
        state: present

    - name: Start and enable MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes
