- name: Install MariaDB on App Tier
  hosts: app
  become: yes

  tasks:

    - name: Update packages
      yum:
        name: "*"
        state: latest

    - name: Install MariaDB
      yum:
        name: mariadb105-server
        state: present

    - name: Start MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes
