- name: Install Nginx
  hosts: web_servers
  become: yes

  tasks:
    - name: Install Nginx
      shell: amazon-linux-extras install nginx1 -y

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes
